javascript:function(){var e="http://wapo.joeydev.com/trust-project/",t="http://wapo.joeydev.com/trust-project/",s=document.location.hostname;(s.indexOf("projects.dev")>=0||s.indexOf("localhost")>=0)&&(e="",t="")
var n=document.createElement("link")
n.setAttribute("rel","stylesheet"),n.setAttribute("href",e+"css/foundation.min.css"),document.getElementsByTagName("head")[0].appendChild(n)
var r=document.createElement("link")
r.setAttribute("rel","stylesheet"),r.setAttribute("href",e+"font-awesome-4.7.0/css/font-awesome.min.css"),document.getElementsByTagName("head")[0].appendChild(r)
var a=document.createElement("link")
a.setAttribute("rel","stylesheet"),a.setAttribute("href",e+"css/trust-sidebar.css"),document.getElementsByTagName("head")[0].appendChild(a)
var o=document.createElement("script")
o.setAttribute("src",t+"js/trust-sidebar.js"),document.body.appendChild(o)}()
